export default {
  common: {
    continue:   'Continue',
    cancel:     'Cancel',
    confirm:    'Confirm',
    back:       'Back',
    loading:    'Loading...',
    error:      'Something went wrong',
    retry:      'Retry',
    logout:     'Log Out',
    seeAll:     'See All',
    markAllRead:'Mark all read',
    support:    'Support',
    version:    'Version',
    bankCode:   'Bank Code',
  },
  auth: {
    login: {
      subtitle:         'Secure Mobile Banking',
      phonePlaceholder: 'Phone Number',
      cta:              'Continue',
      biometricCta:     'Use Biometrics',
    },
    otp: {
      title:    'Verify OTP',
      subtitle: 'Code sent to {{phone}}',
      verify:   'Verify',
      resend:   'Resend OTP',
      resendIn: 'Resend in {{seconds}}s',
    },
    biometric: {
      title:    'Enable {{type}} Login',
      subtitle: 'Log in faster and more securely.',
      enable:   'Enable {{type}}',
      skip:     'Skip for Now',
    },
  },
  dashboard: {
    greeting:           'Good morning 👋',
    myAccounts:         'My Accounts',
    quickActions:       'QUICK ACTIONS',
    recentTransactions: 'Recent Transactions',
    noTransactions:     'No transactions yet',
    actions: {
      transfer: 'Transfer',
      pay:      'Pay Bills',
      topUp:    'Top Up',
      more:     'More',
    },
  },
  transfers: {
    title:       'Fund Transfer',
    from:        'FROM',
    balance:     'Bal',
    accountNum:  'Recipient Account Number',
    accountName: 'Recipient Name',
    amount:      'Amount',
    narration:   'Narration',
    proceed:     'Proceed',
    confirmTitle:'Confirm Transfer',
    confirmMsg:  'Transfer {{currency}} {{amount}} to {{name}}?\n\nNarration: {{narration}}',
    transferNow: 'Transfer Now',
  },
  profile: {
    title:      'My Profile',
    customer:   'Customer',
    fullName:   'Full Name',
    email:      'Email',
    phone:      'Phone',
    kycStatus:  'KYC Status',
    support:    'Support',
  },
  settings: {
    title:          'Settings',
    biometricLogin: 'Biometric Login',
    language:       'Language',
    bankCode:       'Bank Code',
    version:        'Version',
    logoutTitle:    'Log Out',
    logoutMessage:  'Are you sure you want to log out?',
    testSecurity:   '🔒 Test Security Block Screen',
  },
  lock: {
    title:    'Session Locked',
    subtitle: 'Your session has expired.\nEnter your PIN to continue.',
    unlock:   'Unlock with {{type}}',
    logout:   'Log Out',
  },
  notifications: {
    title:  'Notifications',
    empty:  'No notifications yet',
  },
  support: {
    title:   'Support',
    contact: 'CONTACT US',
    call:    'Call Us',
    email:   'Email Us',
    whatsapp:'WhatsApp',
    faqTitle:'FREQUENTLY ASKED QUESTIONS',
    faqs: [
      {
        q: 'How do I reset my transaction PIN?',
        a: 'Go to Profile → Security → Reset PIN. You will receive an OTP to verify your identity.',
      },
      {
        q: 'How long does a transfer take?',
        a: 'Same-bank transfers are instant. Inter-bank transfers take 1–3 business days.',
      },
      {
        q: 'What if I notice an unauthorized transaction?',
        a: 'Call support immediately or freeze your account from Profile → Security → Freeze Account.',
      },
      {
        q: 'How do I enable biometric login?',
        a: 'Go to Settings → Biometric Login and toggle it on.',
      },
    ],
  },
  about: {
    title:    'About',
    platform: 'Secure Mobile Banking Platform',
    appVersion: 'App Version',
    bankCode:   'Bank Code',
    apiVersion: 'API Version',
    suppEmail:  'Support Email',
    suppPhone:  'Support Phone',
    legal:      'LEGAL',
    privacy:    'Privacy Policy',
    terms:      'Terms of Service',
    cookies:    'Cookie Policy',
    footer:     '© {{year}} {{bank}}. All rights reserved.\nPowered by MF Banking Framework',
  },
  security: {
    blocked:  'Device Not Supported',
    subtitle: '{{bank}} requires a secure, unmodified device to protect your account.',
    help:     'Please use an official unmodified device.\nContact support if you believe this is an error.',
  },
  drawer: {
    home:          'Home',
    transfer:      'Transfer',
    profile:       'Profile',
    notifications: 'Notifications',
    support:       'Support',
    about:         'About',
    logout:        'Log Out',
  },
  tabs: {
    home:     'Home',
    transfer: 'Transfer',
    profile:  'Profile',
    settings: 'Settings',
  },
};
