export default {
  common: {
    continue:   'استمرار',
    cancel:     'إلغاء',
    confirm:    'تأكيد',
    back:       'رجوع',
    loading:    'جارٍ التحميل...',
    error:      'حدث خطأ ما',
    retry:      'إعادة المحاولة',
    logout:     'تسجيل الخروج',
    seeAll:     'عرض الكل',
    markAllRead:'تحديد الكل كمقروء',
    support:    'الدعم',
    version:    'الإصدار',
    bankCode:   'رمز البنك',
  },
  auth: {
    login: {
      subtitle:         'الخدمات المصرفية المحمولة الآمنة',
      phonePlaceholder: 'رقم الهاتف',
      cta:              'استمرار',
      biometricCta:     'استخدام البيومترية',
    },
    otp: {
      title:    'التحقق من OTP',
      subtitle: 'تم إرسال الرمز إلى {{phone}}',
      verify:   'تحقق',
      resend:   'إعادة إرسال OTP',
      resendIn: 'إعادة الإرسال خلال {{seconds}} ثانية',
    },
    biometric: {
      title:    'تفعيل تسجيل الدخول بـ{{type}}',
      subtitle: 'تسجيل دخول أسرع وأكثر أماناً.',
      enable:   'تفعيل {{type}}',
      skip:     'تخطي الآن',
    },
  },
  dashboard: {
    greeting:           'صباح الخير 👋',
    myAccounts:         'حساباتي',
    quickActions:       'الإجراءات السريعة',
    recentTransactions: 'المعاملات الأخيرة',
    noTransactions:     'لا توجد معاملات بعد',
    actions: {
      transfer: 'تحويل',
      pay:      'دفع الفواتير',
      topUp:    'إضافة رصيد',
      more:     'المزيد',
    },
  },
  transfers: {
    title:       'تحويل الأموال',
    from:        'من',
    balance:     'الرصيد',
    accountNum:  'رقم حساب المستلم',
    accountName: 'اسم المستلم',
    amount:      'المبلغ',
    narration:   'البيان',
    proceed:     'متابعة',
    confirmTitle:'تأكيد التحويل',
    confirmMsg:  'تحويل {{currency}} {{amount}} إلى {{name}}?\n\nالبيان: {{narration}}',
    transferNow: 'تحويل الآن',
  },
  profile: {
    title:     'ملفي الشخصي',
    customer:  'عميل',
    fullName:  'الاسم الكامل',
    email:     'البريد الإلكتروني',
    phone:     'الهاتف',
    kycStatus: 'حالة KYC',
    support:   'الدعم',
  },
  settings: {
    title:          'الإعدادات',
    biometricLogin: 'تسجيل الدخول البيومتري',
    language:       'اللغة',
    bankCode:       'رمز البنك',
    version:        'الإصدار',
    logoutTitle:    'تسجيل الخروج',
    logoutMessage:  'هل أنت متأكد من تسجيل الخروج؟',
    testSecurity:   '🔒 اختبار شاشة حجب الأمان',
  },
  lock: {
    title:    'الجلسة مقفلة',
    subtitle: 'انتهت جلستك لأمانك.\nأدخل رقم PIN للمتابعة.',
    unlock:   'فتح بـ{{type}}',
    logout:   'تسجيل الخروج',
  },
  notifications: {
    title: 'الإشعارات',
    empty: 'لا توجد إشعارات بعد',
  },
  support: {
    title:    'الدعم',
    contact:  'اتصل بنا',
    call:     'اتصل بنا',
    email:    'راسلنا',
    whatsapp: 'واتساب',
    faqTitle: 'الأسئلة الشائعة',
    faqs: [
      {
        q: 'كيف أعيد تعيين رقم PIN للمعاملات؟',
        a: 'اذهب إلى الملف الشخصي ← الأمان ← إعادة تعيين PIN.',
      },
      {
        q: 'كم يستغرق التحويل؟',
        a: 'التحويلات داخل البنك فورية. التحويلات بين البنوك تستغرق 1-3 أيام عمل.',
      },
      {
        q: 'ماذا أفعل إذا لاحظت معاملة غير مصرح بها؟',
        a: 'اتصل بالدعم فوراً أو جمّد حسابك من الملف الشخصي ← الأمان.',
      },
      {
        q: 'كيف أفعّل تسجيل الدخول البيومتري؟',
        a: 'اذهب إلى الإعدادات ← تسجيل الدخول البيومتري وقم بتفعيله.',
      },
    ],
  },
  about: {
    title:      'حول التطبيق',
    platform:   'منصة الخدمات المصرفية المحمولة الآمنة',
    appVersion: 'إصدار التطبيق',
    bankCode:   'رمز البنك',
    apiVersion: 'إصدار API',
    suppEmail:  'البريد الإلكتروني للدعم',
    suppPhone:  'هاتف الدعم',
    legal:      'قانوني',
    privacy:    'سياسة الخصوصية',
    terms:      'شروط الخدمة',
    cookies:    'سياسة الكوكيز',
    footer:     '© {{year}} {{bank}}. جميع الحقوق محفوظة.\nمدعوم من MF Banking Framework',
  },
  security: {
    blocked:  'الجهاز غير مدعوم',
    subtitle: 'يتطلب {{bank}} جهازاً آمناً وغير معدَّل لحماية حسابك.',
    help:     'يرجى استخدام جهاز رسمي غير معدَّل.\nتواصل مع الدعم إذا كنت تعتقد أن هذا خطأ.',
  },
  drawer: {
    home:          'الرئيسية',
    transfer:      'تحويل',
    profile:       'الملف الشخصي',
    notifications: 'الإشعارات',
    support:       'الدعم',
    about:         'حول التطبيق',
    logout:        'تسجيل الخروج',
  },
  tabs: {
    home:     'الرئيسية',
    transfer: 'تحويل',
    profile:  'الملف الشخصي',
    settings: 'الإعدادات',
  },
};
